#ifndef __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__
#define __ONLINE_GAME_GS_COOLDOWN_CONFIG_H__

//单位为毫秒
#define EMOTE_COOLDOWN_TIME		4000
#define FASHION_COOLDOWN_TIME		1000
#define DROPMONEY_COOLDOWN_TIME		1671
#define DROPITEM_COOLDOWN_TIME  	321	
#define FACEPILL_COOLDOWN_TIME  	300000
#define FACETICKET_COOLDOWN_TIME 	60*1000//3600*1000		//1小时冷却
#define RECURRECT_SCROLL_COOLDOWN_TIME	300000
//#define SOUL_STONE_COOLDOWN_TIME	1800000			//半小时冷却时间
#define SOUL_STONE_COOLDOWN_TIME	18000			//半小时冷却时间
#define RUSH_FLAY_COOLDOWN_TIME		20000			//飞行冲刺冷却时间
#define TOWN_SCROLL_COOLDOWN_TIME	500			//回城符冷却时间
#define ITEM_MOBGEN_COOLDOWN_TIME	3000			//物品生成器的冷却时间
#define QUERY_OTHER_EQUIP_COOLDOWN_TIME	20000			//察看别人装备的冷却时间
#define PET_FOOD_COOLDOWN_TIME		60000			//喂养宠物的冷却时间
#define FIREWORKS_COOLDOWN_TIME		1000			//使用标准烟花的时间
#define SKILLTRIGGER_COOLDOWN_TIME	120000			//使用技能物品的冷却时间
#define REFINE_COOLDOWN_TIME		1000			//精炼和绑定相关的冷却时间
#define DYE_COOLDOWN_TIME		1000			//染色的 冷却时间 
#define CAST_ELF_SKILL_COOLDOWN_TIME		1000		//施放小精灵技能的公共冷却 lgc
#define ELF_CMD_COOLDOWN_TIME	1000			//用于小精灵改变安全状态，注入经验
#define GET_MALL_PRICE_COOLDOWN_TIME	30000	
#define QUERY_OTHER_PROPERTY_COOLDOWN_TIME	5000	//察看别人属性的冷却时间
#define SKILLTRIGGER2_COOLDOWN_TIME			1000	//使用技能物品2的冷却时间
#define EQUIP_FASHION_ITEM_COOLDOWN_TIME	55000	//时装换装冷却时间
#define GET_DIVIDEND_MALL_PRICE_COOLDOWN_TIME	30000	
#define	MULTI_EXCHANGE_ITEM_COOLDOWN_TIME		10000	//整理仓库/包裹冷却
#define TEAM_CONGREGATE_COOLDOWN_TIME					60000	//队伍集结道具使用冷却时间
#define FACTION_CONGREGATE_COOLDOWN_TIME				60000	//帮派集结道具使用冷却时间
#define FACTION_ALLIANCE_CONGREGATE_COOLDOWN_TIME		600000	//帮派集结道具使用冷却时间
#define DPS_DPH_RANK_COOLDOWN_TIME				1000	//获取DPS排行榜冷却时间
#define PLAYER_JOIN_FORCE_COOLDOWN_TIME			60*1000//24*3600*1000
#define PLAYER_LEAVE_FORCE_COOLDOWN_TIME		120*1000//7*24*3600*1000
#define TOGGLE_ONLINE_AWARD_COOLDOWN_TIME		1000
#define COUNTRY_JOIN_APPLY_COOLDOWN_TIME		30000
#define COUNTRY_CHAT_COOLDOWN_TIME 				3000
#define CHANGEDS_COOLDOWN_TIME 					30000
#define TOUCH_QUERY_COOLDOWN_TIME 				1000
#define SWITCH_IN_PARALLEL_WORLD_COOLDOWN_TIME	3000
#define QUERY_PARALLEL_WORLD_COOLDOWN_TIME		3000
#define GIFTCARD_REDEEM_COOLDOWN_TIME 				1000
#define TRICKBATTLE_APPLY_COOLDOWN_TIME			30000
#define AUTOTEAM_SET_GOAL_COOLDOWN_TIME 		5000
#define PLAYER_GATHER_COOLDOWN_TIME				500		//玩家采集的冷却时间，防止外挂重复打断
#define COUNTRYBATTLE_LIVESHOW_COOLDOWN_TIME 	4000
#define PLAYER_QUERY_MAFIA_PVP_COOLDOWN_TIME	5000
#define PLAYER_USE_AUTOSWAP_COOLDOWN_TIME		350

enum 
{
	COOLDOWN_INDEX_NULL,
	COOLDOWN_INDEX_PVP,		//没用，先占位
	COOLDOWN_INDEX_EMOTE,
	COOLDOWN_INDEX_REJUVENATION_POTION,
	COOLDOWN_INDEX_SWITCH_FASHION,
	COOLDOWN_INDEX_DROP_MONEY,
	COOLDOWN_INDEX_DROP_ITEM,
	COOLDOWN_INDEX_FACEPILL,
	COOLDOWN_INDEX_FACETICKET,
	COOLDOWN_INDEX_RECURRECT_SCROLL,
	COOLDOWN_INDEX_SOUL_STONE,
	COOLDOWN_INDEX_HP_POTION,
	COOLDOWN_INDEX_MP_POTION,
	COOLDOWN_INDEX_ANITDOTE_POTION,
	COOLDOWN_INDEX_RUSH_FLY,
	COOLDOWN_INDEX_TOWN_SCROLL,
	COOLDOWN_INDEX_MOV_GEN,
	COOLDOWN_INDEX_QUERY_OTHER_EQUIP,
	COOLDOWN_INDEX_FEED_PET,
	COOLDOWN_INDEX_FIREWORKS,
	COOLDOWN_INDEX_FARCRY,
	COOLDOWN_INDEX_SKILL_TRIGGER,
	COOLDOWN_INDEX_REFINE,
	COOLDOWN_INDEX_DEF_RUNE,
	COOLDOWN_INDEX_AUTO_HP,
	COOLDOWN_INDEX_AUTO_MP,
	COOLDOWN_INDEX_DBL_EXP,
	COOLDOWN_INDEX_DYE,
	COOLDOWN_INDEX_TEAM_RELATION,
	COOLDOWN_INDEX_REFINE_TRANSMIT,
	COOLDOWN_INDEX_CAST_ELF_SKILL,	//lgc
	COOLDOWN_INDEX_ELF_CMD,
	COOLDOWM_INDEX_GET_MALL_PRICE,
	COOLDOWN_INDEX_QUERY_OTHER_PROPERTY,
	COOLDOWN_INDEX_SKILLTRIGGER2,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN0,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN1,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN2,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN3,
	COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN4,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN0,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN1,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN2,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN3,
	COOLDOWN_INDEX_RUNECOMMONCOOLDOWN4,
	COOLDOWN_INDEX_EQUIP_FASHION_ITEM,
	COOLDOWM_INDEX_GET_DIVIDEND_MALL_PRICE,
	COOLDOWN_INDEX_MULTI_EXCHANGE_ITEM,
	COOLDOWN_INDEX_TEAM_CONGREGATE,
	COOLDOWN_INDEX_FACTION_CONGREGATE,
	COOLDOWN_INDEX_DPS_DPH_RANK,
	COOLDOWN_INDEX_PLAYER_JOIN_FORCE,
	COOLDOWN_INDEX_PLAYER_LEAVE_FORCE,
	COOLDOWN_INDEX_TOGGLE_ONLINE_AWARD,
	COOLDOWN_INDEX_COUNTRY_JOIN_APPLY,
	COOLDOWN_INDEX_COUNTRY_CHAT,
	COOLDOWN_INDEX_CHANGEDS,
	COOLDOWN_INDEX_TOUCHTRADE,
	COOLDOWN_INDEX_SWITCH_IN_PARALLEL_WORLD,
	COOLDOWN_INDEX_QUERY_PARALLEL_WORLD,
	COOLDOWN_INDEX_GIFTCARD_REDEEM,
	COOLDOWM_INDEX_TRICKBATTLE_APPLY,
	COOLDOWM_INDEX_AUTOTEAM_SET_GOAL,
	COOLDOWN_INDEX_PLAYER_GATHER,
	COOLDOWN_INDEX_COUNTRYBATTLE_LIVESHOW,
	COOLDOWN_INDEX_QUERY_MAFIA_PVP_INFO,
	
	//joslian
	COOLDOWN_INDEX_PLAYER_USE_AUTOSWAP,
	COOLDOWN_INDEX_FACTION_ALLIANCE_CONGREGATE,
	//joslian end
	
	COOLDOWN_INDEX_COMMONCOOLDOWNSTART = COOLDOWN_INDEX_SKILLCOMMONCOOLDOWN0,

	COOLDOWN_INDEX_CHEATER = 1000,
	COOLDOWN_INDEX_ANTI_CHEAT = 1001,
	COOLDOWN_SKILL_START = 1024,
};

#endif

